// Replaces placeholder plates with images generated by the xAI (Grok) image API.
//   XAI_API_KEY=... node scripts/generate-grok.mjs            (all plates)
//   XAI_API_KEY=... node scripts/generate-grok.mjs hero look-stairwell
// UNTESTED: written against xAI's OpenAI-compatible endpoint (POST /v1/images/generations) but never run,
// because the build sandbox had no key and api.x.ai was blocked. Set XAI_IMAGE_MODEL if the default is retired.
// Output keeps the existing file names and widths, so nothing else in the app changes.
import sharp from 'sharp';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const key = process.env.XAI_API_KEY;
if (!key) {
  console.error('Set XAI_API_KEY in your shell. Do not commit it.');
  process.exit(1);
}
const MODEL = process.env.XAI_IMAGE_MODEL ?? 'grok-2-image';
const manifest = JSON.parse(await readFile(path.join(root, 'src/data/plates.json'), 'utf8'));

// One shared description keeps the featured jacket recognisable across every asset.
const JACKET =
  'a muted oxblood cropped shell jacket with a stand collar, a central zip and two large front pockets, matte technical cotton';
const STYLE =
  'natural late-afternoon light, fine film grain, quiet architectural setting, premium fashion editorial photograph, no text, no logos, no watermark';
const studio = (what) =>
  `Clean product photograph of ${what}, laid flat on pale concrete, soft window light, true colour, sharp textile detail, ${STYLE}`;
const body = (what) =>
  `Full-length photograph of a model wearing ${what}, standing in a concrete passage with an angled shaft of light, ${STYLE}`;
const macro = (what) => `Extreme close-up macro of the fabric of ${what}, raking light, visible weave, ${STYLE}`;

const products = {
  'form-shell-jacket': JACKET,
  'field-wool-overshirt': 'a concrete grey wool overshirt with two chest pockets and a straight hem',
  'heavyweight-tee': 'a chalk-coloured heavyweight cotton tee with a wide neck rib',
  'relaxed-pleat-trouser': 'charcoal relaxed trousers with a single forward pleat and a straight leg',
  'volume-hoodie': 'a washed charcoal hoodie with a deep hood and kangaroo pocket',
  'rib-knit': 'an oat-coloured textured rib knit sweater with a close neck',
};

const prompts = {
  hero: `Wide campaign photograph of a model in ${JACKET}, standing right of centre beneath a concrete overhang, empty shadowed space on the left for text, ${STYLE}`,
  'hero-m': `Tall portrait campaign photograph of a model in ${JACKET} beneath a concrete overhang, subject in the centre, ${STYLE}`,
  'brand-chair': `${JACKET} draped over a simple wooden chair against a plaster wall, ${STYLE}`,
  'jacket-fabric': macro(JACKET),
  'look-stairwell': `${body(`${JACKET} open over a heavyweight chalk tee and charcoal pleated trousers`).replace('concrete passage with an angled shaft of light', 'concrete stairwell at last light')}`,
  'look-passage': `${body('a washed charcoal hoodie under a concrete grey wool overshirt, charcoal trousers')}, wide landscape framing`,
};
for (const [slug, what] of Object.entries(products)) {
  prompts[`${slug}-garment`] = studio(what);
  prompts[`${slug}-body`] = body(what);
  prompts[`${slug}-detail`] = macro(what);
}

const wanted = process.argv.slice(2);
const ids = wanted.length ? wanted : Object.keys(manifest);

for (const id of ids) {
  const meta = manifest[id];
  if (!meta || !prompts[id]) {
    console.warn('skip unknown id', id);
    continue;
  }
  const res = await fetch('https://api.x.ai/v1/images/generations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify({ model: MODEL, prompt: prompts[id], n: 1, response_format: 'b64_json' }),
  });
  if (!res.ok) {
    console.error(id, res.status, await res.text());
    continue;
  }
  const json = await res.json();
  const src = Buffer.from(json.data[0].b64_json, 'base64');
  // The API picks its own aspect ratio, so crop to the slot's ratio with sharp.
  for (const w of meta.widths) {
    await sharp(src)
      .resize({ width: w, height: Math.round((w * meta.h) / meta.w), fit: 'cover', position: 'attention' })
      .jpeg({ quality: 78, mozjpeg: true })
      .toFile(path.join(root, 'public/img', `${id}-${w}.jpg`));
  }
  console.log('generated', id);
}
