import plates from './plates.json';

/**
 * Every picture in the build is a replaceable "plate" generated by scripts/make-plates.mjs.
 * They are procedural textures, not photographs of the garments. Swap the files in
 * public/img for real photography (same id, same aspect ratio) and nothing else changes.
 */
export type PlateId = keyof typeof plates;

export interface ImageRef {
  id: PlateId;
  alt: string;
}

export const plate = (id: PlateId, alt: string): ImageRef => ({ id, alt });

export const plateMeta = (id: PlateId) => plates[id];

export const plateSrc = (id: PlateId, width?: number) => {
  const widths = plates[id].widths;
  const w = width ?? widths[widths.length - 1];
  return `/img/${id}-${w}.jpg`;
};

export const plateSrcSet = (id: PlateId) =>
  plates[id].widths.map((w) => `/img/${id}-${w}.jpg ${w}w`).join(', ');
